spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/historical_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: "your-secret-key-at-least-32-characters-long-for-hs256"
  expirationSeconds: 86400